name = "music-proxy"
main = "music-proxy.ts"
compatibility_date = "2024-12-01"
account_id = "b2a4966ba1851fec69abbe0c6873a219"

[[routes]]
pattern = "music.subdiy.qzz.io/*"
zone_name = "subdiy.qzz.io"
